otp:
  expiration-time-in-sec: 60
  endpoint:
    base: /otp
  validation:
    mock: "true"
    code: "1111"
server:
  port: 8083
  servlet:
    contextPath: /otp
management:
  endpoint:
    health:
      show-details: "ALWAYS"
mail:
  sender: notificaciones-sand@lulobank.com
  bcc: BCClulobank@yopmail.com
  otp-email:
    email-message: "Usa este c\u00F3digo para identificarte en Lulobank: "
    email-subject: "C\u00F3digo de verificaci\u00F3n OTP Lulobank"
operations:
  messages:
    hire-loan:
      message: "Tu codigo para continuar con la aprobacion de tu credito es "
      length: 4
    withdrawal:
      expires: 600
      length: 6
cloud:
  aws:
    stack:
      auto: false
    region:
      static: us-east-1
    end-point:
      uri-notifications: https://sqs.us-east-1.amazonaws.com/848155883266/notifications-v2-sand
    max-number-of-messages: 10
    sqs:
      listeners:
        application-events: https://sqs.us-east-1.amazonaws.com/848155883266/notifications-v2-sand
      endpoint: https://sqs.us-east-1.amazonaws.com/848155883266/
      queue:
        client-alerts-events: https://sqs.us-east-1.amazonaws.com/848155883266/clientAlertsV2-sand
    sns:
      sender-id: Piso19
      max-price: 0.10
      type: Transactional
  google:
    firebase:
      push-endpoint: https://fcm.googleapis.com/
      push-key: asdasdasdasd
events:
  lib:
    controller:
      enable: false
digitalevidence:
  s3:
    evidence: evidencia-digital-sand
services:
  clients:
    url:  http://lbk-nlb-sand-b4ae09a807e738b7.elb.us-east-1.amazonaws.com:8081/
http:
  client:
    baseUrl: http://lbk-nlb-sand-b4ae09a807e738b7.elb.us-east-1.amazonaws.com:8081/
logging:
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss.SSS} | thread=%thread | traceId=%X{traceId} | class=%class{15}.%L | msg="%.-50000m"%n'
  mask-fields:
    complete: '/password,/newpin,/oldpin,/newPassword,/oldPassword'
    partially:
spring:
  application:
    name: "otp-business-capability"
  redis:
    host: cluster-default-name-sand.0cd4jw.clustercfg.use1.cache.amazonaws.com
    port: 6379
  main:
    allow-bean-definition-overriding: true
  security:
    oauth2:
      resourceserver:
        jwt:
          tenantLulo:
            issuer: https://lulobank.com.co
            private-key-value: classpath:private_key.pem
            public-key-value: classpath:public_key.pem
          tenantAWS:
            jwk-set-uri: https://cognito-idp.us-east-1.amazonaws.com/us-east-1_1WmBHEn0a/.well-known/jwks.json
            issuer: https://cognito-idp.us-east-1.amazonaws.com/us-east-1_1WmBHEn0a
            authorized-scope: internal_api/internal_transactions
            authorized-scope-zendesk: zendesk/zendesk